function mdl = fitBayesLda(xtr,ytr)
mdl = fitcdiscr(xtr,ytr,'OptimizeHyperparameters','auto',...
    'HyperparameterOptimizationOptions',...
    struct('AcquisitionFunctionName','expected-improvement-plus',...
    'UseParallel',true,'ShowPlots',false));
end